# Generated by Django 4.2.4 on 2023-08-23 18:15

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("item", "0001_initial"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="Category",
            new_name="Categorys",
        ),
    ]
