# Generated by Django 4.2.4 on 2023-08-23 18:18

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("item", "0002_rename_category_categorys"),
    ]

    operations = [
        migrations.CreateModel(
            name="Category",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=225)),
            ],
        ),
    ]
